// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { Citation } from '../../../../components/common/interfaces/Citation';
import { Region } from '../../../region/content-types/region/region';
import { ObjectifDeveloppementDurable } from '../../../objectif-developpement-durable/content-types/objectif-developpement-durable/objectif-developpement-durable';
import { Situation } from '../../../../components/retour-experience/interfaces/Situation';
import { Calendrier } from '../../../../components/retour-experience/interfaces/Calendrier';
import { SolutionRetourExperience } from '../../../solution-retour-experience/content-types/solution-retour-experience/solution-retour-experience';
import { Contact } from '../../../../components/retour-experience/interfaces/Contact';
import { Media_Plain } from '../../../../common/schemas-to-ts/Media';
import { Citation_Plain } from '../../../../components/common/interfaces/Citation';
import { Region_Plain } from '../../../region/content-types/region/region';
import { ObjectifDeveloppementDurable_Plain } from '../../../objectif-developpement-durable/content-types/objectif-developpement-durable/objectif-developpement-durable';
import { Situation_Plain } from '../../../../components/retour-experience/interfaces/Situation';
import { Calendrier_Plain } from '../../../../components/retour-experience/interfaces/Calendrier';
import { SolutionRetourExperience_Plain } from '../../../solution-retour-experience/content-types/solution-retour-experience/solution-retour-experience';
import { Contact_Plain } from '../../../../components/retour-experience/interfaces/Contact';
import { Citation_NoRelations } from '../../../../components/common/interfaces/Citation';
import { Situation_NoRelations } from '../../../../components/retour-experience/interfaces/Situation';
import { Calendrier_NoRelations } from '../../../../components/retour-experience/interfaces/Calendrier';
import { Contact_NoRelations } from '../../../../components/retour-experience/interfaces/Contact';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export enum ClimatActuel {
  Oceanique = 'oceanique',
  Mediterraneen = 'mediterraneen',
  SemiAride = 'semi_aride',
  SemiContinental = 'semi_continental',
  Equatorial = 'equatorial',
  Tempere = 'tempere',}
export enum ClimatFutur {
  Oceanique = 'oceanique',
  Mediterraneen = 'mediterraneen',
  SemiAride = 'semi_aride',
  SemiContinental = 'semi_continental',
  Equatorial = 'equatorial',
  Tempere = 'tempere',}
export enum Temporalite {
  CourtTerme = 'court_terme',
  MoyenTerme = 'moyen_terme',
  LongTerme = 'long_terme',}

export interface RetourExperience {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    titre: string;
    slug: string;
    image_principale?: { data: Media };
    types_solutions?: any;
    citations: Citation[];
    region?: { data: Region };
    climat_actuel?: ClimatActuel;
    climat_futur?: ClimatFutur;
    echelle?: string;
    temporalite?: Temporalite;
    cout?: string;
    types_espaces?: any;
    retour_experiences: { data: RetourExperience[] };
    odds: { data: ObjectifDeveloppementDurable[] };
    situation_avant?: Situation;
    situation_apres?: Situation;
    calendrier: Calendrier[];
    solution_retour_experiences: { data: SolutionRetourExperience[] };
    description: any;
    porteur?: any;
    contact?: any;
    financement?: any;
    difficultes?: any;
    partenaires?: any;
    ressources?: any;
    credits?: any;
    rank?: number;
    location?: any;
    contacts: Contact[];
    cout_euro?: number;
  };
}
export interface RetourExperience_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  titre: string;
  slug: string;
  image_principale?: Media_Plain;
  types_solutions?: any;
  citations: Citation_Plain[];
  region?: Region_Plain;
  climat_actuel?: ClimatActuel;
  climat_futur?: ClimatFutur;
  echelle?: string;
  temporalite?: Temporalite;
  cout?: string;
  types_espaces?: any;
  retour_experiences: RetourExperience_Plain[];
  odds: ObjectifDeveloppementDurable_Plain[];
  situation_avant?: Situation_Plain;
  situation_apres?: Situation_Plain;
  calendrier: Calendrier_Plain[];
  solution_retour_experiences: SolutionRetourExperience_Plain[];
  description: any;
  porteur?: any;
  contact?: any;
  financement?: any;
  difficultes?: any;
  partenaires?: any;
  ressources?: any;
  credits?: any;
  rank?: number;
  location?: any;
  contacts: Contact_Plain[];
  cout_euro?: number;
}

export interface RetourExperience_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  titre: string;
  slug: string;
  image_principale?: number;
  types_solutions?: any;
  citations: Citation_NoRelations[];
  region?: number;
  climat_actuel?: ClimatActuel;
  climat_futur?: ClimatFutur;
  echelle?: string;
  temporalite?: Temporalite;
  cout?: string;
  types_espaces?: any;
  retour_experiences: number[];
  odds: number[];
  situation_avant?: Situation_NoRelations;
  situation_apres?: Situation_NoRelations;
  calendrier: Calendrier_NoRelations[];
  solution_retour_experiences: number[];
  description: any;
  porteur?: any;
  contact?: any;
  financement?: any;
  difficultes?: any;
  partenaires?: any;
  ressources?: any;
  credits?: any;
  rank?: number;
  location?: any;
  contacts: Contact_NoRelations[];
  cout_euro?: number;
}

export interface RetourExperience_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  titre: string;
  slug: string;
  image_principale?: AdminPanelRelationPropertyModification<Media_Plain>;
  types_solutions?: any;
  citations: Citation_Plain[];
  region?: AdminPanelRelationPropertyModification<Region_Plain>;
  climat_actuel?: ClimatActuel;
  climat_futur?: ClimatFutur;
  echelle?: string;
  temporalite?: Temporalite;
  cout?: string;
  types_espaces?: any;
  retour_experiences: AdminPanelRelationPropertyModification<RetourExperience_Plain>;
  odds: AdminPanelRelationPropertyModification<ObjectifDeveloppementDurable_Plain>;
  situation_avant?: Situation_Plain;
  situation_apres?: Situation_Plain;
  calendrier: Calendrier_Plain[];
  solution_retour_experiences: AdminPanelRelationPropertyModification<SolutionRetourExperience_Plain>;
  description: any;
  porteur?: any;
  contact?: any;
  financement?: any;
  difficultes?: any;
  partenaires?: any;
  ressources?: any;
  credits?: any;
  rank?: number;
  location?: any;
  contacts: Contact_Plain[];
  cout_euro?: number;
}
