/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import contentVersioning from "@notum-cz/strapi-plugin-content-versioning/strapi-admin";
import dragDropContentTypes from "@retikolo/drag-drop-content-types/strapi-admin";
import strapiCloud from "@strapi/plugin-cloud/strapi-admin";
import graphql from "@strapi/plugin-graphql/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import locationField from "strapi-location-field-plugin/strapi-admin";
import multiSelect from "strapi-plugin-multi-select/strapi-admin";
import ckeditor from "../../src/plugins/strapi-plugin-ckeditor/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    "content-versioning": contentVersioning,
    "drag-drop-content-types": dragDropContentTypes,
    "strapi-cloud": strapiCloud,
    graphql: graphql,
    i18n: i18N,
    "users-permissions": usersPermissions,
    "location-field": locationField,
    "multi-select": multiSelect,
    ckeditor: ckeditor,
  },
});
